---
- name: Cluster Status
  hosts: redis
  gather_facts: false

  tasks:

    - name: Redis version
      shell: "redis-server --version | awk '{print $3}'"
      register: redis_version
      changed_when: false

    - name: Memory usage
      shell: "redis-cli INFO memory | grep used_memory_human | cut -d: -f2"
      register: memory
      changed_when: false

    - name: Cluster nodes
      shell: "redis-cli cluster nodes"
      register: nodeinfo
      changed_when: false

    - name: Cluster info
      shell: "redis-cli cluster info"
      register: clusterinfo
      changed_when: false

    - name: Show status
      debug:
        msg:
          node: "{{ inventory_hostname }}"
          version: "{{ redis_version.stdout }}"
          memory: "{{ memory.stdout }}"
          cluster_state: "{{ clusterinfo.stdout_lines }}"
